version: '3'
services:
  pytest:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: pytest  # Comando para executar os testes
  my-streamlit-app:
    build:
      context: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - PORT=8501
